version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 2
      exclude:
        - "@jsse/*"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
    groups:
      dev-dependencies:
        patterns:
          - "*"
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
