packages:
  - packages/geo
  - packages/geojson
  - packages/geotypes
  - packages/srtm
  - packages/utiles
allowBuilds:
  dprint: true
  esbuild: true
onlyBuiltDependencies:
  - dprint
  - esbuild
  - unrs-resolver
